BEGIN;
CREATE INDEX iLoveComputerScience0 ON actor USING btree(first_name);
CREATE INDEX iLoveComputerScience1 ON actor USING hash(first_name);
CREATE INDEX iLoveComputerScience2 ON actor USING btree(last_update);
CREATE INDEX iLoveComputerScience3 ON actor USING hash(last_update);
CREATE INDEX iLoveComputerScience4 ON actor USING btree(actor_id);
CREATE INDEX iLoveComputerScience5 ON actor USING hash(actor_id);
CREATE INDEX iLoveComputerScience6 ON actor USING btree(last_name);
CREATE INDEX iLoveComputerScience7 ON actor USING hash(last_name);
CREATE INDEX iLoveComputerScience8 ON address USING btree(address_id);
CREATE INDEX iLoveComputerScience9 ON address USING hash(address_id);
CREATE INDEX iLoveComputerScience10 ON address USING btree(phone);
CREATE INDEX iLoveComputerScience11 ON address USING hash(phone);
CREATE INDEX iLoveComputerScience12 ON address USING btree(city_id);
CREATE INDEX iLoveComputerScience13 ON address USING hash(city_id);
CREATE INDEX iLoveComputerScience14 ON address USING btree(address2);
CREATE INDEX iLoveComputerScience15 ON address USING hash(address2);
CREATE INDEX iLoveComputerScience16 ON address USING btree(address);
CREATE INDEX iLoveComputerScience17 ON address USING hash(address);
CREATE INDEX iLoveComputerScience18 ON address USING btree(last_update);
CREATE INDEX iLoveComputerScience19 ON address USING hash(last_update);
CREATE INDEX iLoveComputerScience20 ON address USING btree(postal_code);
CREATE INDEX iLoveComputerScience21 ON address USING hash(postal_code);
CREATE INDEX iLoveComputerScience22 ON address USING btree(district);
CREATE INDEX iLoveComputerScience23 ON address USING hash(district);
CREATE INDEX iLoveComputerScience24 ON category USING btree(category_id);
CREATE INDEX iLoveComputerScience25 ON category USING hash(category_id);
CREATE INDEX iLoveComputerScience26 ON category USING btree(name);
CREATE INDEX iLoveComputerScience27 ON category USING hash(name);
CREATE INDEX iLoveComputerScience28 ON category USING btree(last_update);
CREATE INDEX iLoveComputerScience29 ON category USING hash(last_update);
CREATE INDEX iLoveComputerScience30 ON city USING btree(city_id);
CREATE INDEX iLoveComputerScience31 ON city USING hash(city_id);
CREATE INDEX iLoveComputerScience32 ON city USING btree(country_id);
CREATE INDEX iLoveComputerScience33 ON city USING hash(country_id);
CREATE INDEX iLoveComputerScience34 ON city USING btree(last_update);
CREATE INDEX iLoveComputerScience35 ON city USING hash(last_update);
CREATE INDEX iLoveComputerScience36 ON city USING btree(city);
CREATE INDEX iLoveComputerScience37 ON city USING hash(city);
CREATE INDEX iLoveComputerScience38 ON country USING btree(country);
CREATE INDEX iLoveComputerScience39 ON country USING hash(country);
CREATE INDEX iLoveComputerScience40 ON country USING btree(country_id);
CREATE INDEX iLoveComputerScience41 ON country USING hash(country_id);
CREATE INDEX iLoveComputerScience42 ON country USING btree(last_update);
CREATE INDEX iLoveComputerScience43 ON country USING hash(last_update);
CREATE INDEX iLoveComputerScience44 ON customer USING btree(last_name);
CREATE INDEX iLoveComputerScience45 ON customer USING hash(last_name);
CREATE INDEX iLoveComputerScience46 ON customer USING btree(email);
CREATE INDEX iLoveComputerScience47 ON customer USING hash(email);
CREATE INDEX iLoveComputerScience48 ON customer USING btree(address_id);
CREATE INDEX iLoveComputerScience49 ON customer USING hash(address_id);
CREATE INDEX iLoveComputerScience50 ON customer USING btree(active);
CREATE INDEX iLoveComputerScience51 ON customer USING hash(active);
CREATE INDEX iLoveComputerScience52 ON customer USING btree(first_name);
CREATE INDEX iLoveComputerScience53 ON customer USING hash(first_name);
CREATE INDEX iLoveComputerScience54 ON customer USING btree(store_id);
CREATE INDEX iLoveComputerScience55 ON customer USING hash(store_id);
CREATE INDEX iLoveComputerScience56 ON customer USING btree(last_update);
CREATE INDEX iLoveComputerScience57 ON customer USING hash(last_update);
CREATE INDEX iLoveComputerScience58 ON customer USING btree(create_date);
CREATE INDEX iLoveComputerScience59 ON customer USING hash(create_date);
CREATE INDEX iLoveComputerScience60 ON customer USING btree(activebool);
CREATE INDEX iLoveComputerScience61 ON customer USING hash(activebool);
CREATE INDEX iLoveComputerScience62 ON customer USING btree(customer_id);
CREATE INDEX iLoveComputerScience63 ON customer USING hash(customer_id);
CREATE INDEX iLoveComputerScience64 ON film USING btree(title);
CREATE INDEX iLoveComputerScience65 ON film USING hash(title);
CREATE INDEX iLoveComputerScience66 ON film USING btree(length);
CREATE INDEX iLoveComputerScience67 ON film USING hash(length);
CREATE INDEX iLoveComputerScience68 ON film USING btree(rental_duration);
CREATE INDEX iLoveComputerScience69 ON film USING hash(rental_duration);
CREATE INDEX iLoveComputerScience70 ON film USING btree(rental_rate);
CREATE INDEX iLoveComputerScience71 ON film USING hash(rental_rate);
CREATE INDEX iLoveComputerScience72 ON film USING btree(replacement_cost);
CREATE INDEX iLoveComputerScience73 ON film USING hash(replacement_cost);
CREATE INDEX iLoveComputerScience74 ON film USING btree(rating);
CREATE INDEX iLoveComputerScience75 ON film USING hash(rating);
CREATE INDEX iLoveComputerScience76 ON film USING btree(last_update);
CREATE INDEX iLoveComputerScience77 ON film USING hash(last_update);
CREATE INDEX iLoveComputerScience78 ON film USING btree(film_id);
CREATE INDEX iLoveComputerScience79 ON film USING hash(film_id);
CREATE INDEX iLoveComputerScience80 ON film USING btree(language_id);
CREATE INDEX iLoveComputerScience81 ON film USING hash(language_id);
CREATE INDEX iLoveComputerScience82 ON film USING btree(release_year);
CREATE INDEX iLoveComputerScience83 ON film USING hash(release_year);
CREATE INDEX iLoveComputerScience84 ON film USING btree(description);
CREATE INDEX iLoveComputerScience85 ON film USING hash(description);
CREATE INDEX iLoveComputerScience86 ON film_actor USING btree(last_update);
CREATE INDEX iLoveComputerScience87 ON film_actor USING hash(last_update);
CREATE INDEX iLoveComputerScience88 ON film_actor USING btree(film_id);
CREATE INDEX iLoveComputerScience89 ON film_actor USING hash(film_id);
CREATE INDEX iLoveComputerScience90 ON film_actor USING btree(actor_id);
CREATE INDEX iLoveComputerScience91 ON film_actor USING hash(actor_id);
CREATE INDEX iLoveComputerScience92 ON film_category USING btree(category_id);
CREATE INDEX iLoveComputerScience93 ON film_category USING hash(category_id);
CREATE INDEX iLoveComputerScience94 ON film_category USING btree(film_id);
CREATE INDEX iLoveComputerScience95 ON film_category USING hash(film_id);
CREATE INDEX iLoveComputerScience96 ON film_category USING btree(last_update);
CREATE INDEX iLoveComputerScience97 ON film_category USING hash(last_update);
CREATE INDEX iLoveComputerScience98 ON inventory USING btree(film_id);
CREATE INDEX iLoveComputerScience99 ON inventory USING hash(film_id);
CREATE INDEX iLoveComputerScience100 ON inventory USING btree(store_id);
CREATE INDEX iLoveComputerScience101 ON inventory USING hash(store_id);
CREATE INDEX iLoveComputerScience102 ON inventory USING btree(inventory_id);
CREATE INDEX iLoveComputerScience103 ON inventory USING hash(inventory_id);
CREATE INDEX iLoveComputerScience104 ON inventory USING btree(last_update);
CREATE INDEX iLoveComputerScience105 ON inventory USING hash(last_update);
CREATE INDEX iLoveComputerScience106 ON language USING btree(name);
CREATE INDEX iLoveComputerScience107 ON language USING hash(name);
CREATE INDEX iLoveComputerScience108 ON language USING btree(language_id);
CREATE INDEX iLoveComputerScience109 ON language USING hash(language_id);
CREATE INDEX iLoveComputerScience110 ON language USING btree(last_update);
CREATE INDEX iLoveComputerScience111 ON language USING hash(last_update);
CREATE INDEX iLoveComputerScience112 ON payment USING btree(customer_id);
CREATE INDEX iLoveComputerScience113 ON payment USING hash(customer_id);
CREATE INDEX iLoveComputerScience114 ON payment USING btree(staff_id);
CREATE INDEX iLoveComputerScience115 ON payment USING hash(staff_id);
CREATE INDEX iLoveComputerScience116 ON payment USING btree(rental_id);
CREATE INDEX iLoveComputerScience117 ON payment USING hash(rental_id);
CREATE INDEX iLoveComputerScience118 ON payment USING btree(amount);
CREATE INDEX iLoveComputerScience119 ON payment USING hash(amount);
CREATE INDEX iLoveComputerScience120 ON payment USING btree(payment_date);
CREATE INDEX iLoveComputerScience121 ON payment USING hash(payment_date);
CREATE INDEX iLoveComputerScience122 ON payment USING btree(payment_id);
CREATE INDEX iLoveComputerScience123 ON payment USING hash(payment_id);
CREATE INDEX iLoveComputerScience124 ON rental USING btree(rental_date);
CREATE INDEX iLoveComputerScience125 ON rental USING hash(rental_date);
CREATE INDEX iLoveComputerScience126 ON rental USING btree(inventory_id);
CREATE INDEX iLoveComputerScience127 ON rental USING hash(inventory_id);
CREATE INDEX iLoveComputerScience128 ON rental USING btree(customer_id);
CREATE INDEX iLoveComputerScience129 ON rental USING hash(customer_id);
CREATE INDEX iLoveComputerScience130 ON rental USING btree(return_date);
CREATE INDEX iLoveComputerScience131 ON rental USING hash(return_date);
CREATE INDEX iLoveComputerScience132 ON rental USING btree(staff_id);
CREATE INDEX iLoveComputerScience133 ON rental USING hash(staff_id);
CREATE INDEX iLoveComputerScience134 ON rental USING btree(rental_id);
CREATE INDEX iLoveComputerScience135 ON rental USING hash(rental_id);
CREATE INDEX iLoveComputerScience136 ON rental USING btree(last_update);
CREATE INDEX iLoveComputerScience137 ON rental USING hash(last_update);
CREATE INDEX iLoveComputerScience138 ON staff USING btree(first_name);
CREATE INDEX iLoveComputerScience139 ON staff USING hash(first_name);
CREATE INDEX iLoveComputerScience140 ON staff USING btree(last_name);
CREATE INDEX iLoveComputerScience141 ON staff USING hash(last_name);
CREATE INDEX iLoveComputerScience142 ON staff USING btree(address_id);
CREATE INDEX iLoveComputerScience143 ON staff USING hash(address_id);
CREATE INDEX iLoveComputerScience144 ON staff USING btree(email);
CREATE INDEX iLoveComputerScience145 ON staff USING hash(email);
CREATE INDEX iLoveComputerScience146 ON staff USING btree(store_id);
CREATE INDEX iLoveComputerScience147 ON staff USING hash(store_id);
CREATE INDEX iLoveComputerScience148 ON staff USING btree(username);
CREATE INDEX iLoveComputerScience149 ON staff USING hash(username);
CREATE INDEX iLoveComputerScience150 ON staff USING btree(password);
CREATE INDEX iLoveComputerScience151 ON staff USING hash(password);
CREATE INDEX iLoveComputerScience152 ON staff USING btree(picture);
CREATE INDEX iLoveComputerScience153 ON staff USING hash(picture);
CREATE INDEX iLoveComputerScience154 ON staff USING btree(staff_id);
CREATE INDEX iLoveComputerScience155 ON staff USING hash(staff_id);
CREATE INDEX iLoveComputerScience156 ON staff USING btree(active);
CREATE INDEX iLoveComputerScience157 ON staff USING hash(active);
CREATE INDEX iLoveComputerScience158 ON staff USING btree(last_update);
CREATE INDEX iLoveComputerScience159 ON staff USING hash(last_update);
CREATE INDEX iLoveComputerScience160 ON store USING btree(manager_staff_id);
CREATE INDEX iLoveComputerScience161 ON store USING hash(manager_staff_id);
CREATE INDEX iLoveComputerScience162 ON store USING btree(address_id);
CREATE INDEX iLoveComputerScience163 ON store USING hash(address_id);
CREATE INDEX iLoveComputerScience164 ON store USING btree(store_id);
CREATE INDEX iLoveComputerScience165 ON store USING hash(store_id);
CREATE INDEX iLoveComputerScience166 ON store USING btree(last_update);
CREATE INDEX iLoveComputerScience167 ON store USING hash(last_update);
CREATE INDEX iLoveComputerScience168 ON actor USING btree(last_update);
CREATE INDEX iLoveComputerScience169 ON actor USING btree(actor_id);
CREATE INDEX iLoveComputerScience170 ON actor USING btree(last_name);
CREATE INDEX iLoveComputerScience171 ON actor USING btree(last_update, actor_id);
CREATE INDEX iLoveComputerScience172 ON actor USING btree(last_update, last_name);
CREATE INDEX iLoveComputerScience173 ON actor USING btree(actor_id, last_name);
CREATE INDEX iLoveComputerScience174 ON actor USING btree(last_update, actor_id, last_name);
CREATE INDEX iLoveComputerScience175 ON address USING btree(phone);
CREATE INDEX iLoveComputerScience176 ON address USING btree(city_id);
CREATE INDEX iLoveComputerScience177 ON address USING btree(address2);
CREATE INDEX iLoveComputerScience178 ON address USING btree(address);
CREATE INDEX iLoveComputerScience179 ON address USING btree(last_update);
CREATE INDEX iLoveComputerScience180 ON address USING btree(postal_code);
CREATE INDEX iLoveComputerScience181 ON address USING btree(district);
CREATE INDEX iLoveComputerScience182 ON address USING btree(phone, city_id);
CREATE INDEX iLoveComputerScience183 ON address USING btree(phone, address2);
CREATE INDEX iLoveComputerScience184 ON address USING btree(phone, address);
CREATE INDEX iLoveComputerScience185 ON address USING btree(phone, last_update);
CREATE INDEX iLoveComputerScience186 ON address USING btree(phone, postal_code);
CREATE INDEX iLoveComputerScience187 ON address USING btree(phone, district);
CREATE INDEX iLoveComputerScience188 ON address USING btree(city_id, address2);
CREATE INDEX iLoveComputerScience189 ON address USING btree(city_id, address);
CREATE INDEX iLoveComputerScience190 ON address USING btree(city_id, last_update);
CREATE INDEX iLoveComputerScience191 ON address USING btree(city_id, postal_code);
CREATE INDEX iLoveComputerScience192 ON address USING btree(city_id, district);
CREATE INDEX iLoveComputerScience193 ON address USING btree(address2, address);
CREATE INDEX iLoveComputerScience194 ON address USING btree(address2, last_update);
CREATE INDEX iLoveComputerScience195 ON address USING btree(address2, postal_code);
CREATE INDEX iLoveComputerScience196 ON address USING btree(address2, district);
CREATE INDEX iLoveComputerScience197 ON address USING btree(address, last_update);
CREATE INDEX iLoveComputerScience198 ON address USING btree(address, postal_code);
CREATE INDEX iLoveComputerScience199 ON address USING btree(address, district);
CREATE INDEX iLoveComputerScience200 ON address USING btree(last_update, postal_code);
CREATE INDEX iLoveComputerScience201 ON address USING btree(last_update, district);
CREATE INDEX iLoveComputerScience202 ON address USING btree(postal_code, district);
CREATE INDEX iLoveComputerScience203 ON address USING btree(phone, city_id, address2);
CREATE INDEX iLoveComputerScience204 ON address USING btree(phone, city_id, address);
CREATE INDEX iLoveComputerScience205 ON address USING btree(phone, city_id, last_update);
CREATE INDEX iLoveComputerScience206 ON address USING btree(phone, city_id, postal_code);
CREATE INDEX iLoveComputerScience207 ON address USING btree(phone, city_id, district);
CREATE INDEX iLoveComputerScience208 ON address USING btree(phone, address2, address);
CREATE INDEX iLoveComputerScience209 ON address USING btree(phone, address2, last_update);
CREATE INDEX iLoveComputerScience210 ON address USING btree(phone, address2, postal_code);
CREATE INDEX iLoveComputerScience211 ON address USING btree(phone, address2, district);
CREATE INDEX iLoveComputerScience212 ON address USING btree(phone, address, last_update);
CREATE INDEX iLoveComputerScience213 ON address USING btree(phone, address, postal_code);
CREATE INDEX iLoveComputerScience214 ON address USING btree(phone, address, district);
CREATE INDEX iLoveComputerScience215 ON address USING btree(phone, last_update, postal_code);
CREATE INDEX iLoveComputerScience216 ON address USING btree(phone, last_update, district);
CREATE INDEX iLoveComputerScience217 ON address USING btree(phone, postal_code, district);
CREATE INDEX iLoveComputerScience218 ON address USING btree(city_id, address2, address);
CREATE INDEX iLoveComputerScience219 ON address USING btree(city_id, address2, last_update);
CREATE INDEX iLoveComputerScience220 ON address USING btree(city_id, address2, postal_code);
CREATE INDEX iLoveComputerScience221 ON address USING btree(city_id, address2, district);
CREATE INDEX iLoveComputerScience222 ON address USING btree(city_id, address, last_update);
CREATE INDEX iLoveComputerScience223 ON address USING btree(city_id, address, postal_code);
CREATE INDEX iLoveComputerScience224 ON address USING btree(city_id, address, district);
CREATE INDEX iLoveComputerScience225 ON address USING btree(city_id, last_update, postal_code);
CREATE INDEX iLoveComputerScience226 ON address USING btree(city_id, last_update, district);
CREATE INDEX iLoveComputerScience227 ON address USING btree(city_id, postal_code, district);
CREATE INDEX iLoveComputerScience228 ON address USING btree(address2, address, last_update);
CREATE INDEX iLoveComputerScience229 ON address USING btree(address2, address, postal_code);
CREATE INDEX iLoveComputerScience230 ON address USING btree(address2, address, district);
CREATE INDEX iLoveComputerScience231 ON address USING btree(address2, last_update, postal_code);
CREATE INDEX iLoveComputerScience232 ON address USING btree(address2, last_update, district);
CREATE INDEX iLoveComputerScience233 ON address USING btree(address2, postal_code, district);
CREATE INDEX iLoveComputerScience234 ON address USING btree(address, last_update, postal_code);
CREATE INDEX iLoveComputerScience235 ON address USING btree(address, last_update, district);
CREATE INDEX iLoveComputerScience236 ON address USING btree(address, postal_code, district);
CREATE INDEX iLoveComputerScience237 ON address USING btree(last_update, postal_code, district);
CREATE INDEX iLoveComputerScience238 ON category USING btree(name);
CREATE INDEX iLoveComputerScience239 ON category USING btree(last_update);
CREATE INDEX iLoveComputerScience240 ON category USING btree(name, last_update);
CREATE INDEX iLoveComputerScience241 ON city USING btree(country_id);
CREATE INDEX iLoveComputerScience242 ON city USING btree(last_update);
CREATE INDEX iLoveComputerScience243 ON city USING btree(city);
CREATE INDEX iLoveComputerScience244 ON city USING btree(country_id, last_update);
CREATE INDEX iLoveComputerScience245 ON city USING btree(country_id, city);
CREATE INDEX iLoveComputerScience246 ON city USING btree(last_update, city);
CREATE INDEX iLoveComputerScience247 ON city USING btree(country_id, last_update, city);
CREATE INDEX iLoveComputerScience248 ON country USING btree(country_id);
CREATE INDEX iLoveComputerScience249 ON country USING btree(last_update);
CREATE INDEX iLoveComputerScience250 ON country USING btree(country_id, last_update);
CREATE INDEX iLoveComputerScience251 ON customer USING btree(email);
CREATE INDEX iLoveComputerScience252 ON customer USING btree(address_id);
CREATE INDEX iLoveComputerScience253 ON customer USING btree(active);
CREATE INDEX iLoveComputerScience254 ON customer USING btree(first_name);
CREATE INDEX iLoveComputerScience255 ON customer USING btree(store_id);
CREATE INDEX iLoveComputerScience256 ON customer USING btree(last_update);
CREATE INDEX iLoveComputerScience257 ON customer USING btree(create_date);
CREATE INDEX iLoveComputerScience258 ON customer USING btree(activebool);
CREATE INDEX iLoveComputerScience259 ON customer USING btree(customer_id);
CREATE INDEX iLoveComputerScience260 ON customer USING btree(email, address_id);
CREATE INDEX iLoveComputerScience261 ON customer USING btree(email, active);
CREATE INDEX iLoveComputerScience262 ON customer USING btree(email, first_name);
CREATE INDEX iLoveComputerScience263 ON customer USING btree(email, store_id);
CREATE INDEX iLoveComputerScience264 ON customer USING btree(email, last_update);
CREATE INDEX iLoveComputerScience265 ON customer USING btree(email, create_date);
CREATE INDEX iLoveComputerScience266 ON customer USING btree(email, activebool);
CREATE INDEX iLoveComputerScience267 ON customer USING btree(email, customer_id);
CREATE INDEX iLoveComputerScience268 ON customer USING btree(address_id, active);
CREATE INDEX iLoveComputerScience269 ON customer USING btree(address_id, first_name);
CREATE INDEX iLoveComputerScience270 ON customer USING btree(address_id, store_id);
CREATE INDEX iLoveComputerScience271 ON customer USING btree(address_id, last_update);
CREATE INDEX iLoveComputerScience272 ON customer USING btree(address_id, create_date);
CREATE INDEX iLoveComputerScience273 ON customer USING btree(address_id, activebool);
CREATE INDEX iLoveComputerScience274 ON customer USING btree(address_id, customer_id);
CREATE INDEX iLoveComputerScience275 ON customer USING btree(active, first_name);
CREATE INDEX iLoveComputerScience276 ON customer USING btree(active, store_id);
CREATE INDEX iLoveComputerScience277 ON customer USING btree(active, last_update);
CREATE INDEX iLoveComputerScience278 ON customer USING btree(active, create_date);
CREATE INDEX iLoveComputerScience279 ON customer USING btree(active, activebool);
CREATE INDEX iLoveComputerScience280 ON customer USING btree(active, customer_id);
CREATE INDEX iLoveComputerScience281 ON customer USING btree(first_name, store_id);
CREATE INDEX iLoveComputerScience282 ON customer USING btree(first_name, last_update);
CREATE INDEX iLoveComputerScience283 ON customer USING btree(first_name, create_date);
CREATE INDEX iLoveComputerScience284 ON customer USING btree(first_name, activebool);
CREATE INDEX iLoveComputerScience285 ON customer USING btree(first_name, customer_id);
CREATE INDEX iLoveComputerScience286 ON customer USING btree(store_id, last_update);
CREATE INDEX iLoveComputerScience287 ON customer USING btree(store_id, create_date);
CREATE INDEX iLoveComputerScience288 ON customer USING btree(store_id, activebool);
CREATE INDEX iLoveComputerScience289 ON customer USING btree(store_id, customer_id);
CREATE INDEX iLoveComputerScience290 ON customer USING btree(last_update, create_date);
CREATE INDEX iLoveComputerScience291 ON customer USING btree(last_update, activebool);
CREATE INDEX iLoveComputerScience292 ON customer USING btree(last_update, customer_id);
CREATE INDEX iLoveComputerScience293 ON customer USING btree(create_date, activebool);
CREATE INDEX iLoveComputerScience294 ON customer USING btree(create_date, customer_id);
CREATE INDEX iLoveComputerScience295 ON customer USING btree(activebool, customer_id);
CREATE INDEX iLoveComputerScience296 ON customer USING btree(email, address_id, active);
CREATE INDEX iLoveComputerScience297 ON customer USING btree(email, address_id, first_name);
CREATE INDEX iLoveComputerScience298 ON customer USING btree(email, address_id, store_id);
CREATE INDEX iLoveComputerScience299 ON customer USING btree(email, address_id, last_update);
CREATE INDEX iLoveComputerScience300 ON customer USING btree(email, address_id, create_date);
CREATE INDEX iLoveComputerScience301 ON customer USING btree(email, address_id, activebool);
CREATE INDEX iLoveComputerScience302 ON customer USING btree(email, address_id, customer_id);
CREATE INDEX iLoveComputerScience303 ON customer USING btree(email, active, first_name);
CREATE INDEX iLoveComputerScience304 ON customer USING btree(email, active, store_id);
CREATE INDEX iLoveComputerScience305 ON customer USING btree(email, active, last_update);
CREATE INDEX iLoveComputerScience306 ON customer USING btree(email, active, create_date);
CREATE INDEX iLoveComputerScience307 ON customer USING btree(email, active, activebool);
CREATE INDEX iLoveComputerScience308 ON customer USING btree(email, active, customer_id);
CREATE INDEX iLoveComputerScience309 ON customer USING btree(email, first_name, store_id);
CREATE INDEX iLoveComputerScience310 ON customer USING btree(email, first_name, last_update);
CREATE INDEX iLoveComputerScience311 ON customer USING btree(email, first_name, create_date);
CREATE INDEX iLoveComputerScience312 ON customer USING btree(email, first_name, activebool);
CREATE INDEX iLoveComputerScience313 ON customer USING btree(email, first_name, customer_id);
CREATE INDEX iLoveComputerScience314 ON customer USING btree(email, store_id, last_update);
CREATE INDEX iLoveComputerScience315 ON customer USING btree(email, store_id, create_date);
CREATE INDEX iLoveComputerScience316 ON customer USING btree(email, store_id, activebool);
CREATE INDEX iLoveComputerScience317 ON customer USING btree(email, store_id, customer_id);
CREATE INDEX iLoveComputerScience318 ON customer USING btree(email, last_update, create_date);
CREATE INDEX iLoveComputerScience319 ON customer USING btree(email, last_update, activebool);
CREATE INDEX iLoveComputerScience320 ON customer USING btree(email, last_update, customer_id);
CREATE INDEX iLoveComputerScience321 ON customer USING btree(email, create_date, activebool);
CREATE INDEX iLoveComputerScience322 ON customer USING btree(email, create_date, customer_id);
CREATE INDEX iLoveComputerScience323 ON customer USING btree(email, activebool, customer_id);
CREATE INDEX iLoveComputerScience324 ON customer USING btree(address_id, active, first_name);
CREATE INDEX iLoveComputerScience325 ON customer USING btree(address_id, active, store_id);
CREATE INDEX iLoveComputerScience326 ON customer USING btree(address_id, active, last_update);
CREATE INDEX iLoveComputerScience327 ON customer USING btree(address_id, active, create_date);
CREATE INDEX iLoveComputerScience328 ON customer USING btree(address_id, active, activebool);
CREATE INDEX iLoveComputerScience329 ON customer USING btree(address_id, active, customer_id);
CREATE INDEX iLoveComputerScience330 ON customer USING btree(address_id, first_name, store_id);
CREATE INDEX iLoveComputerScience331 ON customer USING btree(address_id, first_name, last_update);
CREATE INDEX iLoveComputerScience332 ON customer USING btree(address_id, first_name, create_date);
CREATE INDEX iLoveComputerScience333 ON customer USING btree(address_id, first_name, activebool);
CREATE INDEX iLoveComputerScience334 ON customer USING btree(address_id, first_name, customer_id);
CREATE INDEX iLoveComputerScience335 ON customer USING btree(address_id, store_id, last_update);
CREATE INDEX iLoveComputerScience336 ON customer USING btree(address_id, store_id, create_date);
CREATE INDEX iLoveComputerScience337 ON customer USING btree(address_id, store_id, activebool);
CREATE INDEX iLoveComputerScience338 ON customer USING btree(address_id, store_id, customer_id);
CREATE INDEX iLoveComputerScience339 ON customer USING btree(address_id, last_update, create_date);
CREATE INDEX iLoveComputerScience340 ON customer USING btree(address_id, last_update, activebool);
CREATE INDEX iLoveComputerScience341 ON customer USING btree(address_id, last_update, customer_id);
CREATE INDEX iLoveComputerScience342 ON customer USING btree(address_id, create_date, activebool);
CREATE INDEX iLoveComputerScience343 ON customer USING btree(address_id, create_date, customer_id);
CREATE INDEX iLoveComputerScience344 ON customer USING btree(address_id, activebool, customer_id);
CREATE INDEX iLoveComputerScience345 ON customer USING btree(active, first_name, store_id);
CREATE INDEX iLoveComputerScience346 ON customer USING btree(active, first_name, last_update);
CREATE INDEX iLoveComputerScience347 ON customer USING btree(active, first_name, create_date);
CREATE INDEX iLoveComputerScience348 ON customer USING btree(active, first_name, activebool);
CREATE INDEX iLoveComputerScience349 ON customer USING btree(active, first_name, customer_id);
CREATE INDEX iLoveComputerScience350 ON customer USING btree(active, store_id, last_update);
CREATE INDEX iLoveComputerScience351 ON customer USING btree(active, store_id, create_date);
CREATE INDEX iLoveComputerScience352 ON customer USING btree(active, store_id, activebool);
CREATE INDEX iLoveComputerScience353 ON customer USING btree(active, store_id, customer_id);
CREATE INDEX iLoveComputerScience354 ON customer USING btree(active, last_update, create_date);
CREATE INDEX iLoveComputerScience355 ON customer USING btree(active, last_update, activebool);
CREATE INDEX iLoveComputerScience356 ON customer USING btree(active, last_update, customer_id);
CREATE INDEX iLoveComputerScience357 ON customer USING btree(active, create_date, activebool);
CREATE INDEX iLoveComputerScience358 ON customer USING btree(active, create_date, customer_id);
CREATE INDEX iLoveComputerScience359 ON customer USING btree(active, activebool, customer_id);
CREATE INDEX iLoveComputerScience360 ON customer USING btree(first_name, store_id, last_update);
CREATE INDEX iLoveComputerScience361 ON customer USING btree(first_name, store_id, create_date);
CREATE INDEX iLoveComputerScience362 ON customer USING btree(first_name, store_id, activebool);
CREATE INDEX iLoveComputerScience363 ON customer USING btree(first_name, store_id, customer_id);
CREATE INDEX iLoveComputerScience364 ON customer USING btree(first_name, last_update, create_date);
CREATE INDEX iLoveComputerScience365 ON customer USING btree(first_name, last_update, activebool);
CREATE INDEX iLoveComputerScience366 ON customer USING btree(first_name, last_update, customer_id);
CREATE INDEX iLoveComputerScience367 ON customer USING btree(first_name, create_date, activebool);
CREATE INDEX iLoveComputerScience368 ON customer USING btree(first_name, create_date, customer_id);
CREATE INDEX iLoveComputerScience369 ON customer USING btree(first_name, activebool, customer_id);
CREATE INDEX iLoveComputerScience370 ON customer USING btree(store_id, last_update, create_date);
CREATE INDEX iLoveComputerScience371 ON customer USING btree(store_id, last_update, activebool);
CREATE INDEX iLoveComputerScience372 ON customer USING btree(store_id, last_update, customer_id);
CREATE INDEX iLoveComputerScience373 ON customer USING btree(store_id, create_date, activebool);
CREATE INDEX iLoveComputerScience374 ON customer USING btree(store_id, create_date, customer_id);
CREATE INDEX iLoveComputerScience375 ON customer USING btree(store_id, activebool, customer_id);
CREATE INDEX iLoveComputerScience376 ON customer USING btree(last_update, create_date, activebool);
CREATE INDEX iLoveComputerScience377 ON customer USING btree(last_update, create_date, customer_id);
CREATE INDEX iLoveComputerScience378 ON customer USING btree(last_update, activebool, customer_id);
CREATE INDEX iLoveComputerScience379 ON customer USING btree(create_date, activebool, customer_id);
CREATE INDEX iLoveComputerScience380 ON film USING btree(length);
CREATE INDEX iLoveComputerScience381 ON film USING btree(rental_duration);
CREATE INDEX iLoveComputerScience382 ON film USING btree(rental_rate);
CREATE INDEX iLoveComputerScience383 ON film USING btree(replacement_cost);
CREATE INDEX iLoveComputerScience384 ON film USING btree(rating);
CREATE INDEX iLoveComputerScience385 ON film USING btree(last_update);
CREATE INDEX iLoveComputerScience386 ON film USING btree(film_id);
CREATE INDEX iLoveComputerScience387 ON film USING btree(language_id);
CREATE INDEX iLoveComputerScience388 ON film USING btree(release_year);
CREATE INDEX iLoveComputerScience389 ON film USING btree(description);
CREATE INDEX iLoveComputerScience390 ON film USING btree(length, rental_duration);
CREATE INDEX iLoveComputerScience391 ON film USING btree(length, rental_rate);
CREATE INDEX iLoveComputerScience392 ON film USING btree(length, replacement_cost);
CREATE INDEX iLoveComputerScience393 ON film USING btree(length, rating);
CREATE INDEX iLoveComputerScience394 ON film USING btree(length, last_update);
CREATE INDEX iLoveComputerScience395 ON film USING btree(length, film_id);
CREATE INDEX iLoveComputerScience396 ON film USING btree(length, language_id);
CREATE INDEX iLoveComputerScience397 ON film USING btree(length, release_year);
CREATE INDEX iLoveComputerScience398 ON film USING btree(length, description);
CREATE INDEX iLoveComputerScience399 ON film USING btree(rental_duration, rental_rate);
CREATE INDEX iLoveComputerScience400 ON film USING btree(rental_duration, replacement_cost);
CREATE INDEX iLoveComputerScience401 ON film USING btree(rental_duration, rating);
CREATE INDEX iLoveComputerScience402 ON film USING btree(rental_duration, last_update);
CREATE INDEX iLoveComputerScience403 ON film USING btree(rental_duration, film_id);
CREATE INDEX iLoveComputerScience404 ON film USING btree(rental_duration, language_id);
CREATE INDEX iLoveComputerScience405 ON film USING btree(rental_duration, release_year);
CREATE INDEX iLoveComputerScience406 ON film USING btree(rental_duration, description);
CREATE INDEX iLoveComputerScience407 ON film USING btree(rental_rate, replacement_cost);
CREATE INDEX iLoveComputerScience408 ON film USING btree(rental_rate, rating);
CREATE INDEX iLoveComputerScience409 ON film USING btree(rental_rate, last_update);
CREATE INDEX iLoveComputerScience410 ON film USING btree(rental_rate, film_id);
CREATE INDEX iLoveComputerScience411 ON film USING btree(rental_rate, language_id);
CREATE INDEX iLoveComputerScience412 ON film USING btree(rental_rate, release_year);
CREATE INDEX iLoveComputerScience413 ON film USING btree(rental_rate, description);
CREATE INDEX iLoveComputerScience414 ON film USING btree(replacement_cost, rating);
CREATE INDEX iLoveComputerScience415 ON film USING btree(replacement_cost, last_update);
CREATE INDEX iLoveComputerScience416 ON film USING btree(replacement_cost, film_id);
CREATE INDEX iLoveComputerScience417 ON film USING btree(replacement_cost, language_id);
CREATE INDEX iLoveComputerScience418 ON film USING btree(replacement_cost, release_year);
CREATE INDEX iLoveComputerScience419 ON film USING btree(replacement_cost, description);
CREATE INDEX iLoveComputerScience420 ON film USING btree(rating, last_update);
CREATE INDEX iLoveComputerScience421 ON film USING btree(rating, film_id);
CREATE INDEX iLoveComputerScience422 ON film USING btree(rating, language_id);
CREATE INDEX iLoveComputerScience423 ON film USING btree(rating, release_year);
CREATE INDEX iLoveComputerScience424 ON film USING btree(rating, description);
CREATE INDEX iLoveComputerScience425 ON film USING btree(last_update, film_id);
CREATE INDEX iLoveComputerScience426 ON film USING btree(last_update, language_id);
CREATE INDEX iLoveComputerScience427 ON film USING btree(last_update, release_year);
CREATE INDEX iLoveComputerScience428 ON film USING btree(last_update, description);
CREATE INDEX iLoveComputerScience429 ON film USING btree(film_id, language_id);
CREATE INDEX iLoveComputerScience430 ON film USING btree(film_id, release_year);
CREATE INDEX iLoveComputerScience431 ON film USING btree(film_id, description);
CREATE INDEX iLoveComputerScience432 ON film USING btree(language_id, release_year);
CREATE INDEX iLoveComputerScience433 ON film USING btree(language_id, description);
CREATE INDEX iLoveComputerScience434 ON film USING btree(release_year, description);
CREATE INDEX iLoveComputerScience435 ON film USING btree(length, rental_duration, rental_rate);
CREATE INDEX iLoveComputerScience436 ON film USING btree(length, rental_duration, replacement_cost);
CREATE INDEX iLoveComputerScience437 ON film USING btree(length, rental_duration, rating);
CREATE INDEX iLoveComputerScience438 ON film USING btree(length, rental_duration, last_update);
CREATE INDEX iLoveComputerScience439 ON film USING btree(length, rental_duration, film_id);
CREATE INDEX iLoveComputerScience440 ON film USING btree(length, rental_duration, language_id);
CREATE INDEX iLoveComputerScience441 ON film USING btree(length, rental_duration, release_year);
CREATE INDEX iLoveComputerScience442 ON film USING btree(length, rental_duration, description);
CREATE INDEX iLoveComputerScience443 ON film USING btree(length, rental_rate, replacement_cost);
CREATE INDEX iLoveComputerScience444 ON film USING btree(length, rental_rate, rating);
CREATE INDEX iLoveComputerScience445 ON film USING btree(length, rental_rate, last_update);
CREATE INDEX iLoveComputerScience446 ON film USING btree(length, rental_rate, film_id);
CREATE INDEX iLoveComputerScience447 ON film USING btree(length, rental_rate, language_id);
CREATE INDEX iLoveComputerScience448 ON film USING btree(length, rental_rate, release_year);
CREATE INDEX iLoveComputerScience449 ON film USING btree(length, rental_rate, description);
CREATE INDEX iLoveComputerScience450 ON film USING btree(length, replacement_cost, rating);
CREATE INDEX iLoveComputerScience451 ON film USING btree(length, replacement_cost, last_update);
CREATE INDEX iLoveComputerScience452 ON film USING btree(length, replacement_cost, film_id);
CREATE INDEX iLoveComputerScience453 ON film USING btree(length, replacement_cost, language_id);
CREATE INDEX iLoveComputerScience454 ON film USING btree(length, replacement_cost, release_year);
CREATE INDEX iLoveComputerScience455 ON film USING btree(length, replacement_cost, description);
CREATE INDEX iLoveComputerScience456 ON film USING btree(length, rating, last_update);
CREATE INDEX iLoveComputerScience457 ON film USING btree(length, rating, film_id);
CREATE INDEX iLoveComputerScience458 ON film USING btree(length, rating, language_id);
CREATE INDEX iLoveComputerScience459 ON film USING btree(length, rating, release_year);
CREATE INDEX iLoveComputerScience460 ON film USING btree(length, rating, description);
CREATE INDEX iLoveComputerScience461 ON film USING btree(length, last_update, film_id);
CREATE INDEX iLoveComputerScience462 ON film USING btree(length, last_update, language_id);
CREATE INDEX iLoveComputerScience463 ON film USING btree(length, last_update, release_year);
CREATE INDEX iLoveComputerScience464 ON film USING btree(length, last_update, description);
CREATE INDEX iLoveComputerScience465 ON film USING btree(length, film_id, language_id);
CREATE INDEX iLoveComputerScience466 ON film USING btree(length, film_id, release_year);
CREATE INDEX iLoveComputerScience467 ON film USING btree(length, film_id, description);
CREATE INDEX iLoveComputerScience468 ON film USING btree(length, language_id, release_year);
CREATE INDEX iLoveComputerScience469 ON film USING btree(length, language_id, description);
CREATE INDEX iLoveComputerScience470 ON film USING btree(length, release_year, description);
CREATE INDEX iLoveComputerScience471 ON film USING btree(rental_duration, rental_rate, replacement_cost);
CREATE INDEX iLoveComputerScience472 ON film USING btree(rental_duration, rental_rate, rating);
CREATE INDEX iLoveComputerScience473 ON film USING btree(rental_duration, rental_rate, last_update);
CREATE INDEX iLoveComputerScience474 ON film USING btree(rental_duration, rental_rate, film_id);
CREATE INDEX iLoveComputerScience475 ON film USING btree(rental_duration, rental_rate, language_id);
CREATE INDEX iLoveComputerScience476 ON film USING btree(rental_duration, rental_rate, release_year);
CREATE INDEX iLoveComputerScience477 ON film USING btree(rental_duration, rental_rate, description);
CREATE INDEX iLoveComputerScience478 ON film USING btree(rental_duration, replacement_cost, rating);
CREATE INDEX iLoveComputerScience479 ON film USING btree(rental_duration, replacement_cost, last_update);
CREATE INDEX iLoveComputerScience480 ON film USING btree(rental_duration, replacement_cost, film_id);
CREATE INDEX iLoveComputerScience481 ON film USING btree(rental_duration, replacement_cost, language_id);
CREATE INDEX iLoveComputerScience482 ON film USING btree(rental_duration, replacement_cost, release_year);
CREATE INDEX iLoveComputerScience483 ON film USING btree(rental_duration, replacement_cost, description);
CREATE INDEX iLoveComputerScience484 ON film USING btree(rental_duration, rating, last_update);
CREATE INDEX iLoveComputerScience485 ON film USING btree(rental_duration, rating, film_id);
CREATE INDEX iLoveComputerScience486 ON film USING btree(rental_duration, rating, language_id);
CREATE INDEX iLoveComputerScience487 ON film USING btree(rental_duration, rating, release_year);
CREATE INDEX iLoveComputerScience488 ON film USING btree(rental_duration, rating, description);
CREATE INDEX iLoveComputerScience489 ON film USING btree(rental_duration, last_update, film_id);
CREATE INDEX iLoveComputerScience490 ON film USING btree(rental_duration, last_update, language_id);
CREATE INDEX iLoveComputerScience491 ON film USING btree(rental_duration, last_update, release_year);
CREATE INDEX iLoveComputerScience492 ON film USING btree(rental_duration, last_update, description);
CREATE INDEX iLoveComputerScience493 ON film USING btree(rental_duration, film_id, language_id);
CREATE INDEX iLoveComputerScience494 ON film USING btree(rental_duration, film_id, release_year);
CREATE INDEX iLoveComputerScience495 ON film USING btree(rental_duration, film_id, description);
CREATE INDEX iLoveComputerScience496 ON film USING btree(rental_duration, language_id, release_year);
CREATE INDEX iLoveComputerScience497 ON film USING btree(rental_duration, language_id, description);
CREATE INDEX iLoveComputerScience498 ON film USING btree(rental_duration, release_year, description);
CREATE INDEX iLoveComputerScience499 ON film USING btree(rental_rate, replacement_cost, rating);
CREATE INDEX iLoveComputerScience500 ON film USING btree(rental_rate, replacement_cost, last_update);
CREATE INDEX iLoveComputerScience501 ON film USING btree(rental_rate, replacement_cost, film_id);
CREATE INDEX iLoveComputerScience502 ON film USING btree(rental_rate, replacement_cost, language_id);
CREATE INDEX iLoveComputerScience503 ON film USING btree(rental_rate, replacement_cost, release_year);
CREATE INDEX iLoveComputerScience504 ON film USING btree(rental_rate, replacement_cost, description);
CREATE INDEX iLoveComputerScience505 ON film USING btree(rental_rate, rating, last_update);
CREATE INDEX iLoveComputerScience506 ON film USING btree(rental_rate, rating, film_id);
CREATE INDEX iLoveComputerScience507 ON film USING btree(rental_rate, rating, language_id);
CREATE INDEX iLoveComputerScience508 ON film USING btree(rental_rate, rating, release_year);
CREATE INDEX iLoveComputerScience509 ON film USING btree(rental_rate, rating, description);
CREATE INDEX iLoveComputerScience510 ON film USING btree(rental_rate, last_update, film_id);
CREATE INDEX iLoveComputerScience511 ON film USING btree(rental_rate, last_update, language_id);
CREATE INDEX iLoveComputerScience512 ON film USING btree(rental_rate, last_update, release_year);
CREATE INDEX iLoveComputerScience513 ON film USING btree(rental_rate, last_update, description);
CREATE INDEX iLoveComputerScience514 ON film USING btree(rental_rate, film_id, language_id);
CREATE INDEX iLoveComputerScience515 ON film USING btree(rental_rate, film_id, release_year);
CREATE INDEX iLoveComputerScience516 ON film USING btree(rental_rate, film_id, description);
CREATE INDEX iLoveComputerScience517 ON film USING btree(rental_rate, language_id, release_year);
CREATE INDEX iLoveComputerScience518 ON film USING btree(rental_rate, language_id, description);
CREATE INDEX iLoveComputerScience519 ON film USING btree(rental_rate, release_year, description);
CREATE INDEX iLoveComputerScience520 ON film USING btree(replacement_cost, rating, last_update);
CREATE INDEX iLoveComputerScience521 ON film USING btree(replacement_cost, rating, film_id);
CREATE INDEX iLoveComputerScience522 ON film USING btree(replacement_cost, rating, language_id);
CREATE INDEX iLoveComputerScience523 ON film USING btree(replacement_cost, rating, release_year);
CREATE INDEX iLoveComputerScience524 ON film USING btree(replacement_cost, rating, description);
CREATE INDEX iLoveComputerScience525 ON film USING btree(replacement_cost, last_update, film_id);
CREATE INDEX iLoveComputerScience526 ON film USING btree(replacement_cost, last_update, language_id);
CREATE INDEX iLoveComputerScience527 ON film USING btree(replacement_cost, last_update, release_year);
CREATE INDEX iLoveComputerScience528 ON film USING btree(replacement_cost, last_update, description);
CREATE INDEX iLoveComputerScience529 ON film USING btree(replacement_cost, film_id, language_id);
CREATE INDEX iLoveComputerScience530 ON film USING btree(replacement_cost, film_id, release_year);
CREATE INDEX iLoveComputerScience531 ON film USING btree(replacement_cost, film_id, description);
CREATE INDEX iLoveComputerScience532 ON film USING btree(replacement_cost, language_id, release_year);
CREATE INDEX iLoveComputerScience533 ON film USING btree(replacement_cost, language_id, description);
CREATE INDEX iLoveComputerScience534 ON film USING btree(replacement_cost, release_year, description);
CREATE INDEX iLoveComputerScience535 ON film USING btree(rating, last_update, film_id);
CREATE INDEX iLoveComputerScience536 ON film USING btree(rating, last_update, language_id);
CREATE INDEX iLoveComputerScience537 ON film USING btree(rating, last_update, release_year);
CREATE INDEX iLoveComputerScience538 ON film USING btree(rating, last_update, description);
CREATE INDEX iLoveComputerScience539 ON film USING btree(rating, film_id, language_id);
CREATE INDEX iLoveComputerScience540 ON film USING btree(rating, film_id, release_year);
CREATE INDEX iLoveComputerScience541 ON film USING btree(rating, film_id, description);
CREATE INDEX iLoveComputerScience542 ON film USING btree(rating, language_id, release_year);
CREATE INDEX iLoveComputerScience543 ON film USING btree(rating, language_id, description);
CREATE INDEX iLoveComputerScience544 ON film USING btree(rating, release_year, description);
CREATE INDEX iLoveComputerScience545 ON film USING btree(last_update, film_id, language_id);
CREATE INDEX iLoveComputerScience546 ON film USING btree(last_update, film_id, release_year);
CREATE INDEX iLoveComputerScience547 ON film USING btree(last_update, film_id, description);
CREATE INDEX iLoveComputerScience548 ON film USING btree(last_update, language_id, release_year);
CREATE INDEX iLoveComputerScience549 ON film USING btree(last_update, language_id, description);
CREATE INDEX iLoveComputerScience550 ON film USING btree(last_update, release_year, description);
CREATE INDEX iLoveComputerScience551 ON film USING btree(film_id, language_id, release_year);
CREATE INDEX iLoveComputerScience552 ON film USING btree(film_id, language_id, description);
CREATE INDEX iLoveComputerScience553 ON film USING btree(film_id, release_year, description);
CREATE INDEX iLoveComputerScience554 ON film USING btree(language_id, release_year, description);
CREATE INDEX iLoveComputerScience555 ON film_actor USING btree(film_id);
CREATE INDEX iLoveComputerScience556 ON film_actor USING btree(actor_id);
CREATE INDEX iLoveComputerScience557 ON film_actor USING btree(film_id, actor_id);
CREATE INDEX iLoveComputerScience558 ON film_category USING btree(film_id);
CREATE INDEX iLoveComputerScience559 ON film_category USING btree(last_update);
CREATE INDEX iLoveComputerScience560 ON film_category USING btree(film_id, last_update);
CREATE INDEX iLoveComputerScience561 ON inventory USING btree(store_id);
CREATE INDEX iLoveComputerScience562 ON inventory USING btree(inventory_id);
CREATE INDEX iLoveComputerScience563 ON inventory USING btree(last_update);
CREATE INDEX iLoveComputerScience564 ON inventory USING btree(store_id, inventory_id);
CREATE INDEX iLoveComputerScience565 ON inventory USING btree(store_id, last_update);
CREATE INDEX iLoveComputerScience566 ON inventory USING btree(inventory_id, last_update);
CREATE INDEX iLoveComputerScience567 ON inventory USING btree(store_id, inventory_id, last_update);
CREATE INDEX iLoveComputerScience568 ON language USING btree(language_id);
CREATE INDEX iLoveComputerScience569 ON language USING btree(last_update);
CREATE INDEX iLoveComputerScience570 ON language USING btree(language_id, last_update);
CREATE INDEX iLoveComputerScience571 ON payment USING btree(staff_id);
CREATE INDEX iLoveComputerScience572 ON payment USING btree(rental_id);
CREATE INDEX iLoveComputerScience573 ON payment USING btree(amount);
CREATE INDEX iLoveComputerScience574 ON payment USING btree(payment_date);
CREATE INDEX iLoveComputerScience575 ON payment USING btree(payment_id);
CREATE INDEX iLoveComputerScience576 ON payment USING btree(staff_id, rental_id);
CREATE INDEX iLoveComputerScience577 ON payment USING btree(staff_id, amount);
CREATE INDEX iLoveComputerScience578 ON payment USING btree(staff_id, payment_date);
CREATE INDEX iLoveComputerScience579 ON payment USING btree(staff_id, payment_id);
CREATE INDEX iLoveComputerScience580 ON payment USING btree(rental_id, amount);
CREATE INDEX iLoveComputerScience581 ON payment USING btree(rental_id, payment_date);
CREATE INDEX iLoveComputerScience582 ON payment USING btree(rental_id, payment_id);
CREATE INDEX iLoveComputerScience583 ON payment USING btree(amount, payment_date);
CREATE INDEX iLoveComputerScience584 ON payment USING btree(amount, payment_id);
CREATE INDEX iLoveComputerScience585 ON payment USING btree(payment_date, payment_id);
CREATE INDEX iLoveComputerScience586 ON payment USING btree(staff_id, rental_id, amount);
CREATE INDEX iLoveComputerScience587 ON payment USING btree(staff_id, rental_id, payment_date);
CREATE INDEX iLoveComputerScience588 ON payment USING btree(staff_id, rental_id, payment_id);
CREATE INDEX iLoveComputerScience589 ON payment USING btree(staff_id, amount, payment_date);
CREATE INDEX iLoveComputerScience590 ON payment USING btree(staff_id, amount, payment_id);
CREATE INDEX iLoveComputerScience591 ON payment USING btree(staff_id, payment_date, payment_id);
CREATE INDEX iLoveComputerScience592 ON payment USING btree(rental_id, amount, payment_date);
CREATE INDEX iLoveComputerScience593 ON payment USING btree(rental_id, amount, payment_id);
CREATE INDEX iLoveComputerScience594 ON payment USING btree(rental_id, payment_date, payment_id);
CREATE INDEX iLoveComputerScience595 ON payment USING btree(amount, payment_date, payment_id);
CREATE INDEX iLoveComputerScience596 ON rental USING btree(inventory_id);
CREATE INDEX iLoveComputerScience597 ON rental USING btree(customer_id);
CREATE INDEX iLoveComputerScience598 ON rental USING btree(return_date);
CREATE INDEX iLoveComputerScience599 ON rental USING btree(staff_id);
CREATE INDEX iLoveComputerScience600 ON rental USING btree(rental_id);
CREATE INDEX iLoveComputerScience601 ON rental USING btree(last_update);
CREATE INDEX iLoveComputerScience602 ON rental USING btree(inventory_id, customer_id);
CREATE INDEX iLoveComputerScience603 ON rental USING btree(inventory_id, return_date);
CREATE INDEX iLoveComputerScience604 ON rental USING btree(inventory_id, staff_id);
CREATE INDEX iLoveComputerScience605 ON rental USING btree(inventory_id, rental_id);
CREATE INDEX iLoveComputerScience606 ON rental USING btree(inventory_id, last_update);
CREATE INDEX iLoveComputerScience607 ON rental USING btree(customer_id, return_date);
CREATE INDEX iLoveComputerScience608 ON rental USING btree(customer_id, staff_id);
CREATE INDEX iLoveComputerScience609 ON rental USING btree(customer_id, rental_id);
CREATE INDEX iLoveComputerScience610 ON rental USING btree(customer_id, last_update);
CREATE INDEX iLoveComputerScience611 ON rental USING btree(return_date, staff_id);
CREATE INDEX iLoveComputerScience612 ON rental USING btree(return_date, rental_id);
CREATE INDEX iLoveComputerScience613 ON rental USING btree(return_date, last_update);
CREATE INDEX iLoveComputerScience614 ON rental USING btree(staff_id, rental_id);
CREATE INDEX iLoveComputerScience615 ON rental USING btree(staff_id, last_update);
CREATE INDEX iLoveComputerScience616 ON rental USING btree(rental_id, last_update);
CREATE INDEX iLoveComputerScience617 ON rental USING btree(inventory_id, customer_id, return_date);
CREATE INDEX iLoveComputerScience618 ON rental USING btree(inventory_id, customer_id, staff_id);
CREATE INDEX iLoveComputerScience619 ON rental USING btree(inventory_id, customer_id, rental_id);
CREATE INDEX iLoveComputerScience620 ON rental USING btree(inventory_id, customer_id, last_update);
CREATE INDEX iLoveComputerScience621 ON rental USING btree(inventory_id, return_date, staff_id);
CREATE INDEX iLoveComputerScience622 ON rental USING btree(inventory_id, return_date, rental_id);
CREATE INDEX iLoveComputerScience623 ON rental USING btree(inventory_id, return_date, last_update);
CREATE INDEX iLoveComputerScience624 ON rental USING btree(inventory_id, staff_id, rental_id);
CREATE INDEX iLoveComputerScience625 ON rental USING btree(inventory_id, staff_id, last_update);
CREATE INDEX iLoveComputerScience626 ON rental USING btree(inventory_id, rental_id, last_update);
CREATE INDEX iLoveComputerScience627 ON rental USING btree(customer_id, return_date, staff_id);
CREATE INDEX iLoveComputerScience628 ON rental USING btree(customer_id, return_date, rental_id);
CREATE INDEX iLoveComputerScience629 ON rental USING btree(customer_id, return_date, last_update);
CREATE INDEX iLoveComputerScience630 ON rental USING btree(customer_id, staff_id, rental_id);
CREATE INDEX iLoveComputerScience631 ON rental USING btree(customer_id, staff_id, last_update);
CREATE INDEX iLoveComputerScience632 ON rental USING btree(customer_id, rental_id, last_update);
CREATE INDEX iLoveComputerScience633 ON rental USING btree(return_date, staff_id, rental_id);
CREATE INDEX iLoveComputerScience634 ON rental USING btree(return_date, staff_id, last_update);
CREATE INDEX iLoveComputerScience635 ON rental USING btree(return_date, rental_id, last_update);
CREATE INDEX iLoveComputerScience636 ON rental USING btree(staff_id, rental_id, last_update);
CREATE INDEX iLoveComputerScience637 ON staff USING btree(last_name);
CREATE INDEX iLoveComputerScience638 ON staff USING btree(address_id);
CREATE INDEX iLoveComputerScience639 ON staff USING btree(email);
CREATE INDEX iLoveComputerScience640 ON staff USING btree(store_id);
CREATE INDEX iLoveComputerScience641 ON staff USING btree(username);
CREATE INDEX iLoveComputerScience642 ON staff USING btree(password);
CREATE INDEX iLoveComputerScience643 ON staff USING btree(picture);
CREATE INDEX iLoveComputerScience644 ON staff USING btree(staff_id);
CREATE INDEX iLoveComputerScience645 ON staff USING btree(active);
CREATE INDEX iLoveComputerScience646 ON staff USING btree(last_update);
CREATE INDEX iLoveComputerScience647 ON staff USING btree(last_name, address_id);
CREATE INDEX iLoveComputerScience648 ON staff USING btree(last_name, email);
CREATE INDEX iLoveComputerScience649 ON staff USING btree(last_name, store_id);
CREATE INDEX iLoveComputerScience650 ON staff USING btree(last_name, username);
CREATE INDEX iLoveComputerScience651 ON staff USING btree(last_name, password);
CREATE INDEX iLoveComputerScience652 ON staff USING btree(last_name, picture);
CREATE INDEX iLoveComputerScience653 ON staff USING btree(last_name, staff_id);
CREATE INDEX iLoveComputerScience654 ON staff USING btree(last_name, active);
CREATE INDEX iLoveComputerScience655 ON staff USING btree(last_name, last_update);
CREATE INDEX iLoveComputerScience656 ON staff USING btree(address_id, email);
CREATE INDEX iLoveComputerScience657 ON staff USING btree(address_id, store_id);
CREATE INDEX iLoveComputerScience658 ON staff USING btree(address_id, username);
CREATE INDEX iLoveComputerScience659 ON staff USING btree(address_id, password);
CREATE INDEX iLoveComputerScience660 ON staff USING btree(address_id, picture);
CREATE INDEX iLoveComputerScience661 ON staff USING btree(address_id, staff_id);
CREATE INDEX iLoveComputerScience662 ON staff USING btree(address_id, active);
CREATE INDEX iLoveComputerScience663 ON staff USING btree(address_id, last_update);
CREATE INDEX iLoveComputerScience664 ON staff USING btree(email, store_id);
CREATE INDEX iLoveComputerScience665 ON staff USING btree(email, username);
CREATE INDEX iLoveComputerScience666 ON staff USING btree(email, password);
CREATE INDEX iLoveComputerScience667 ON staff USING btree(email, picture);
CREATE INDEX iLoveComputerScience668 ON staff USING btree(email, staff_id);
CREATE INDEX iLoveComputerScience669 ON staff USING btree(email, active);
CREATE INDEX iLoveComputerScience670 ON staff USING btree(email, last_update);
CREATE INDEX iLoveComputerScience671 ON staff USING btree(store_id, username);
CREATE INDEX iLoveComputerScience672 ON staff USING btree(store_id, password);
CREATE INDEX iLoveComputerScience673 ON staff USING btree(store_id, picture);
CREATE INDEX iLoveComputerScience674 ON staff USING btree(store_id, staff_id);
CREATE INDEX iLoveComputerScience675 ON staff USING btree(store_id, active);
CREATE INDEX iLoveComputerScience676 ON staff USING btree(store_id, last_update);
CREATE INDEX iLoveComputerScience677 ON staff USING btree(username, password);
CREATE INDEX iLoveComputerScience678 ON staff USING btree(username, picture);
CREATE INDEX iLoveComputerScience679 ON staff USING btree(username, staff_id);
CREATE INDEX iLoveComputerScience680 ON staff USING btree(username, active);
CREATE INDEX iLoveComputerScience681 ON staff USING btree(username, last_update);
CREATE INDEX iLoveComputerScience682 ON staff USING btree(password, picture);
CREATE INDEX iLoveComputerScience683 ON staff USING btree(password, staff_id);
CREATE INDEX iLoveComputerScience684 ON staff USING btree(password, active);
CREATE INDEX iLoveComputerScience685 ON staff USING btree(password, last_update);
CREATE INDEX iLoveComputerScience686 ON staff USING btree(picture, staff_id);
CREATE INDEX iLoveComputerScience687 ON staff USING btree(picture, active);
CREATE INDEX iLoveComputerScience688 ON staff USING btree(picture, last_update);
CREATE INDEX iLoveComputerScience689 ON staff USING btree(staff_id, active);
CREATE INDEX iLoveComputerScience690 ON staff USING btree(staff_id, last_update);
CREATE INDEX iLoveComputerScience691 ON staff USING btree(active, last_update);
CREATE INDEX iLoveComputerScience692 ON staff USING btree(last_name, address_id, email);
CREATE INDEX iLoveComputerScience693 ON staff USING btree(last_name, address_id, store_id);
CREATE INDEX iLoveComputerScience694 ON staff USING btree(last_name, address_id, username);
CREATE INDEX iLoveComputerScience695 ON staff USING btree(last_name, address_id, password);
CREATE INDEX iLoveComputerScience696 ON staff USING btree(last_name, address_id, picture);
CREATE INDEX iLoveComputerScience697 ON staff USING btree(last_name, address_id, staff_id);
CREATE INDEX iLoveComputerScience698 ON staff USING btree(last_name, address_id, active);
CREATE INDEX iLoveComputerScience699 ON staff USING btree(last_name, address_id, last_update);
CREATE INDEX iLoveComputerScience700 ON staff USING btree(last_name, email, store_id);
CREATE INDEX iLoveComputerScience701 ON staff USING btree(last_name, email, username);
CREATE INDEX iLoveComputerScience702 ON staff USING btree(last_name, email, password);
CREATE INDEX iLoveComputerScience703 ON staff USING btree(last_name, email, picture);
CREATE INDEX iLoveComputerScience704 ON staff USING btree(last_name, email, staff_id);
CREATE INDEX iLoveComputerScience705 ON staff USING btree(last_name, email, active);
CREATE INDEX iLoveComputerScience706 ON staff USING btree(last_name, email, last_update);
CREATE INDEX iLoveComputerScience707 ON staff USING btree(last_name, store_id, username);
CREATE INDEX iLoveComputerScience708 ON staff USING btree(last_name, store_id, password);
CREATE INDEX iLoveComputerScience709 ON staff USING btree(last_name, store_id, picture);
CREATE INDEX iLoveComputerScience710 ON staff USING btree(last_name, store_id, staff_id);
CREATE INDEX iLoveComputerScience711 ON staff USING btree(last_name, store_id, active);
CREATE INDEX iLoveComputerScience712 ON staff USING btree(last_name, store_id, last_update);
CREATE INDEX iLoveComputerScience713 ON staff USING btree(last_name, username, password);
CREATE INDEX iLoveComputerScience714 ON staff USING btree(last_name, username, picture);
CREATE INDEX iLoveComputerScience715 ON staff USING btree(last_name, username, staff_id);
CREATE INDEX iLoveComputerScience716 ON staff USING btree(last_name, username, active);
CREATE INDEX iLoveComputerScience717 ON staff USING btree(last_name, username, last_update);
CREATE INDEX iLoveComputerScience718 ON staff USING btree(last_name, password, picture);
CREATE INDEX iLoveComputerScience719 ON staff USING btree(last_name, password, staff_id);
CREATE INDEX iLoveComputerScience720 ON staff USING btree(last_name, password, active);
CREATE INDEX iLoveComputerScience721 ON staff USING btree(last_name, password, last_update);
CREATE INDEX iLoveComputerScience722 ON staff USING btree(last_name, picture, staff_id);
CREATE INDEX iLoveComputerScience723 ON staff USING btree(last_name, picture, active);
CREATE INDEX iLoveComputerScience724 ON staff USING btree(last_name, picture, last_update);
CREATE INDEX iLoveComputerScience725 ON staff USING btree(last_name, staff_id, active);
CREATE INDEX iLoveComputerScience726 ON staff USING btree(last_name, staff_id, last_update);
CREATE INDEX iLoveComputerScience727 ON staff USING btree(last_name, active, last_update);
CREATE INDEX iLoveComputerScience728 ON staff USING btree(address_id, email, store_id);
CREATE INDEX iLoveComputerScience729 ON staff USING btree(address_id, email, username);
CREATE INDEX iLoveComputerScience730 ON staff USING btree(address_id, email, password);
CREATE INDEX iLoveComputerScience731 ON staff USING btree(address_id, email, picture);
CREATE INDEX iLoveComputerScience732 ON staff USING btree(address_id, email, staff_id);
CREATE INDEX iLoveComputerScience733 ON staff USING btree(address_id, email, active);
CREATE INDEX iLoveComputerScience734 ON staff USING btree(address_id, email, last_update);
CREATE INDEX iLoveComputerScience735 ON staff USING btree(address_id, store_id, username);
CREATE INDEX iLoveComputerScience736 ON staff USING btree(address_id, store_id, password);
CREATE INDEX iLoveComputerScience737 ON staff USING btree(address_id, store_id, picture);
CREATE INDEX iLoveComputerScience738 ON staff USING btree(address_id, store_id, staff_id);
CREATE INDEX iLoveComputerScience739 ON staff USING btree(address_id, store_id, active);
CREATE INDEX iLoveComputerScience740 ON staff USING btree(address_id, store_id, last_update);
CREATE INDEX iLoveComputerScience741 ON staff USING btree(address_id, username, password);
CREATE INDEX iLoveComputerScience742 ON staff USING btree(address_id, username, picture);
CREATE INDEX iLoveComputerScience743 ON staff USING btree(address_id, username, staff_id);
CREATE INDEX iLoveComputerScience744 ON staff USING btree(address_id, username, active);
CREATE INDEX iLoveComputerScience745 ON staff USING btree(address_id, username, last_update);
CREATE INDEX iLoveComputerScience746 ON staff USING btree(address_id, password, picture);
CREATE INDEX iLoveComputerScience747 ON staff USING btree(address_id, password, staff_id);
CREATE INDEX iLoveComputerScience748 ON staff USING btree(address_id, password, active);
CREATE INDEX iLoveComputerScience749 ON staff USING btree(address_id, password, last_update);
CREATE INDEX iLoveComputerScience750 ON staff USING btree(address_id, picture, staff_id);
CREATE INDEX iLoveComputerScience751 ON staff USING btree(address_id, picture, active);
CREATE INDEX iLoveComputerScience752 ON staff USING btree(address_id, picture, last_update);
CREATE INDEX iLoveComputerScience753 ON staff USING btree(address_id, staff_id, active);
CREATE INDEX iLoveComputerScience754 ON staff USING btree(address_id, staff_id, last_update);
CREATE INDEX iLoveComputerScience755 ON staff USING btree(address_id, active, last_update);
CREATE INDEX iLoveComputerScience756 ON staff USING btree(email, store_id, username);
CREATE INDEX iLoveComputerScience757 ON staff USING btree(email, store_id, password);
CREATE INDEX iLoveComputerScience758 ON staff USING btree(email, store_id, picture);
CREATE INDEX iLoveComputerScience759 ON staff USING btree(email, store_id, staff_id);
CREATE INDEX iLoveComputerScience760 ON staff USING btree(email, store_id, active);
CREATE INDEX iLoveComputerScience761 ON staff USING btree(email, store_id, last_update);
CREATE INDEX iLoveComputerScience762 ON staff USING btree(email, username, password);
CREATE INDEX iLoveComputerScience763 ON staff USING btree(email, username, picture);
CREATE INDEX iLoveComputerScience764 ON staff USING btree(email, username, staff_id);
CREATE INDEX iLoveComputerScience765 ON staff USING btree(email, username, active);
CREATE INDEX iLoveComputerScience766 ON staff USING btree(email, username, last_update);
CREATE INDEX iLoveComputerScience767 ON staff USING btree(email, password, picture);
CREATE INDEX iLoveComputerScience768 ON staff USING btree(email, password, staff_id);
CREATE INDEX iLoveComputerScience769 ON staff USING btree(email, password, active);
CREATE INDEX iLoveComputerScience770 ON staff USING btree(email, password, last_update);
CREATE INDEX iLoveComputerScience771 ON staff USING btree(email, picture, staff_id);
CREATE INDEX iLoveComputerScience772 ON staff USING btree(email, picture, active);
CREATE INDEX iLoveComputerScience773 ON staff USING btree(email, picture, last_update);
CREATE INDEX iLoveComputerScience774 ON staff USING btree(email, staff_id, active);
CREATE INDEX iLoveComputerScience775 ON staff USING btree(email, staff_id, last_update);
CREATE INDEX iLoveComputerScience776 ON staff USING btree(email, active, last_update);
CREATE INDEX iLoveComputerScience777 ON staff USING btree(store_id, username, password);
CREATE INDEX iLoveComputerScience778 ON staff USING btree(store_id, username, picture);
CREATE INDEX iLoveComputerScience779 ON staff USING btree(store_id, username, staff_id);
CREATE INDEX iLoveComputerScience780 ON staff USING btree(store_id, username, active);
CREATE INDEX iLoveComputerScience781 ON staff USING btree(store_id, username, last_update);
CREATE INDEX iLoveComputerScience782 ON staff USING btree(store_id, password, picture);
CREATE INDEX iLoveComputerScience783 ON staff USING btree(store_id, password, staff_id);
CREATE INDEX iLoveComputerScience784 ON staff USING btree(store_id, password, active);
CREATE INDEX iLoveComputerScience785 ON staff USING btree(store_id, password, last_update);
CREATE INDEX iLoveComputerScience786 ON staff USING btree(store_id, picture, staff_id);
CREATE INDEX iLoveComputerScience787 ON staff USING btree(store_id, picture, active);
CREATE INDEX iLoveComputerScience788 ON staff USING btree(store_id, picture, last_update);
CREATE INDEX iLoveComputerScience789 ON staff USING btree(store_id, staff_id, active);
CREATE INDEX iLoveComputerScience790 ON staff USING btree(store_id, staff_id, last_update);
CREATE INDEX iLoveComputerScience791 ON staff USING btree(store_id, active, last_update);
CREATE INDEX iLoveComputerScience792 ON staff USING btree(username, password, picture);
CREATE INDEX iLoveComputerScience793 ON staff USING btree(username, password, staff_id);
CREATE INDEX iLoveComputerScience794 ON staff USING btree(username, password, active);
CREATE INDEX iLoveComputerScience795 ON staff USING btree(username, password, last_update);
CREATE INDEX iLoveComputerScience796 ON staff USING btree(username, picture, staff_id);
CREATE INDEX iLoveComputerScience797 ON staff USING btree(username, picture, active);
CREATE INDEX iLoveComputerScience798 ON staff USING btree(username, picture, last_update);
CREATE INDEX iLoveComputerScience799 ON staff USING btree(username, staff_id, active);
CREATE INDEX iLoveComputerScience800 ON staff USING btree(username, staff_id, last_update);
CREATE INDEX iLoveComputerScience801 ON staff USING btree(username, active, last_update);
CREATE INDEX iLoveComputerScience802 ON staff USING btree(password, picture, staff_id);
CREATE INDEX iLoveComputerScience803 ON staff USING btree(password, picture, active);
CREATE INDEX iLoveComputerScience804 ON staff USING btree(password, picture, last_update);
CREATE INDEX iLoveComputerScience805 ON staff USING btree(password, staff_id, active);
CREATE INDEX iLoveComputerScience806 ON staff USING btree(password, staff_id, last_update);
CREATE INDEX iLoveComputerScience807 ON staff USING btree(password, active, last_update);
CREATE INDEX iLoveComputerScience808 ON staff USING btree(picture, staff_id, active);
CREATE INDEX iLoveComputerScience809 ON staff USING btree(picture, staff_id, last_update);
CREATE INDEX iLoveComputerScience810 ON staff USING btree(picture, active, last_update);
CREATE INDEX iLoveComputerScience811 ON staff USING btree(staff_id, active, last_update);
CREATE INDEX iLoveComputerScience812 ON store USING btree(address_id);
CREATE INDEX iLoveComputerScience813 ON store USING btree(store_id);
CREATE INDEX iLoveComputerScience814 ON store USING btree(last_update);
CREATE INDEX iLoveComputerScience815 ON store USING btree(address_id, store_id);
CREATE INDEX iLoveComputerScience816 ON store USING btree(address_id, last_update);
CREATE INDEX iLoveComputerScience817 ON store USING btree(store_id, last_update);
CREATE INDEX iLoveComputerScience818 ON store USING btree(address_id, store_id, last_update);
EXPLAIN ANALYZE
SELECT r1.staff_id, p1.payment_date
FROM rental r1, payment p1
WHERE r1.rental_id = p1.rental_id AND
NOT EXISTS (SELECT 1 FROM rental r2, customer c WHERE r2.customer_id =
c.customer_id and active = 1 and r2.last_update > r1.last_update);
EXPLAIN ANALYZE
SELECT title, release_year
FROM film f1
WHERE f1.rental_rate > (SELECT AVG(f2.rental_rate) FROM film f2 WHERE
f1.release_year = f2.release_year);
EXPLAIN ANALYZE
SELECT f.title, f.release_year, (SELECT SUM(p.amount) FROM payment p, rental
r1, inventory i1 WHERE p.rental_id = r1.rental_id AND r1.inventory_id =
i1.inventory_id AND i1.film_id = f.film_id)
FROM film f
WHERE NOT EXISTS (SELECT c.first_name, count(*) FROM customer c, rental r2,
inventory i1, film f1, film_actor fa, actor a
WHERE c.customer_id = r2.customer_id AND r2.inventory_id = i1.inventory_id AND
i1.film_id = f1.film_id and f1.rating in ('PG-13','NC-17') AND f1.film_id =
fa.film_id AND f1.film_id = f.film_id AND fa.actor_id = a.actor_id and
a.first_name = c.first_name GROUP BY c.first_name HAVING count(*) >2);
ROLLBACK;
